# Generated by Django 6.0.4 on 2026-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes_app', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='destino',
            new_name='region',
        ),
        migrations.AddField(
            model_name='viaje',
            name='sitio_turistico',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
