# Generated by Django 6.0.4 on 2026-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes_app', '0005_rename_destino_viaje_region_viaje_sitio_turistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='pais',
            field=models.CharField(default='Perú', max_length=100),
            preserve_default=False,
        ),
    ]
